
package com.sas.wsdl.swiftCheckReport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AmlSwiftCheckReport", targetNamespace = "http://swiftCheck.webservice.sas.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AmlSwiftCheckReport {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.sas.wsdl.swiftCheckReport.SwiftCheckReportOutputBean
     */
    @WebMethod(operationName = "SwiftCheckReport")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SwiftCheckReport", targetNamespace = "http://swiftCheck.webservice.sas.com/", className = "com.sas.wsdl.swiftCheckReport.SwiftCheckReport")
    @ResponseWrapper(localName = "SwiftCheckReportResponse", targetNamespace = "http://swiftCheck.webservice.sas.com/", className = "com.sas.wsdl.swiftCheckReport.SwiftCheckReportResponse")
    public SwiftCheckReportOutputBean swiftCheckReport(
        @WebParam(name = "arg0", targetNamespace = "")
        SwiftCheckReportInputBean arg0);

}
