
package com.dataflux.wsdl.archserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.dataflux.xsd.archserver.ObjectFactory;
import com.dataflux.xsd.archserver.TableIn;
import com.dataflux.xsd.archserver.TableOut;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataManagementServicePortType", targetNamespace = "http://archserver.wsdl.dataflux.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataManagementServicePortType {


    /**
     * 
     * @param table
     * @return
     *     returns com.dataflux.xsd.archserver.TableOut
     */
    @WebMethod(operationName = "datasvc_MatchCode.ddf_in", action = "MatchCode.ddf*1*5965C8A6A036990A")
    @WebResult(name = "table_", targetNamespace = "")
    @RequestWrapper(localName = "datasvc_MatchCode.ddf_in", targetNamespace = "archserver.xsd.dataflux.com", className = "com.dataflux.xsd.archserver.Request")
    @ResponseWrapper(localName = "datasvc_MatchCode.ddf_out", targetNamespace = "archserver.xsd.dataflux.com", className = "com.dataflux.xsd.archserver.Response")
    public TableOut datasvcMatchCodeDdfIn(
        @WebParam(name = "table_", targetNamespace = "")
        TableIn table);

}
