
package com.sas.wsdl.swiftcheck;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AmlSwiftCheckImplService", targetNamespace = "http://swiftCheck.webservice.sas.com/", wsdlLocation = "http://localhost:8080/AmlCheck/ws/amlSwiftCheck?wsdl")
public class AmlSwiftCheckImplService
    extends Service
{

    private final static URL AMLSWIFTCHECKIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AMLSWIFTCHECKIMPLSERVICE_EXCEPTION;
    private final static QName AMLSWIFTCHECKIMPLSERVICE_QNAME = new QName("http://swiftCheck.webservice.sas.com/", "AmlSwiftCheckImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/AmlCheck/ws/amlSwiftCheck?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AMLSWIFTCHECKIMPLSERVICE_WSDL_LOCATION = url;
        AMLSWIFTCHECKIMPLSERVICE_EXCEPTION = e;
    }

    public AmlSwiftCheckImplService() {
        super(__getWsdlLocation(), AMLSWIFTCHECKIMPLSERVICE_QNAME);
    }

    public AmlSwiftCheckImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AMLSWIFTCHECKIMPLSERVICE_QNAME, features);
    }

    public AmlSwiftCheckImplService(URL wsdlLocation) {
        super(wsdlLocation, AMLSWIFTCHECKIMPLSERVICE_QNAME);
    }

    public AmlSwiftCheckImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AMLSWIFTCHECKIMPLSERVICE_QNAME, features);
    }

    public AmlSwiftCheckImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AmlSwiftCheckImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AmlSwiftCheck
     */
    @WebEndpoint(name = "AmlSwiftCheckImplPort")
    public AmlSwiftCheck getAmlSwiftCheckImplPort() {
        return super.getPort(new QName("http://swiftCheck.webservice.sas.com/", "AmlSwiftCheckImplPort"), AmlSwiftCheck.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AmlSwiftCheck
     */
    @WebEndpoint(name = "AmlSwiftCheckImplPort")
    public AmlSwiftCheck getAmlSwiftCheckImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://swiftCheck.webservice.sas.com/", "AmlSwiftCheckImplPort"), AmlSwiftCheck.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AMLSWIFTCHECKIMPLSERVICE_EXCEPTION!= null) {
            throw AMLSWIFTCHECKIMPLSERVICE_EXCEPTION;
        }
        return AMLSWIFTCHECKIMPLSERVICE_WSDL_LOCATION;
    }

}
