
package com.sas.wsdl.swiftcheck;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.sas.webservice.swiftCheck.bean.SwiftCheckInputBean;
import com.sas.webservice.swiftCheck.bean.SwiftCheckOutputBean;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AmlSwiftCheck", targetNamespace = "http://swiftCheck.webservice.sas.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AmlSwiftCheck {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.sas.wsdl.swiftcheck.SwiftCheckOutputBean
     */
    @WebMethod(operationName = "SwiftAsyncCheck")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SwiftAsyncCheck", targetNamespace = "http://swiftCheck.webservice.sas.com/", className = "com.sas.wsdl.swiftcheck.SwiftAsyncCheck")
    @ResponseWrapper(localName = "SwiftAsyncCheckResponse", targetNamespace = "http://swiftCheck.webservice.sas.com/", className = "com.sas.wsdl.swiftcheck.SwiftAsyncCheckResponse")
    public SwiftCheckOutputBean swiftAsyncCheck(
        @WebParam(name = "arg0", targetNamespace = "")
        SwiftCheckInputBean arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sas.wsdl.swiftcheck.SwiftCheckOutputBean
     */
    @WebMethod(operationName = "SwiftCheck")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SwiftCheck", targetNamespace = "http://swiftCheck.webservice.sas.com/", className = "com.sas.wsdl.swiftcheck.SwiftCheck")
    @ResponseWrapper(localName = "SwiftCheckResponse", targetNamespace = "http://swiftCheck.webservice.sas.com/", className = "com.sas.wsdl.swiftcheck.SwiftCheckResponse")
    public SwiftCheckOutputBean swiftCheck(
        @WebParam(name = "arg0", targetNamespace = "")
        SwiftCheckInputBean arg0);

}
