
package com.eai.wsdl.sendRecv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EAIService", targetNamespace = "http://www.bot.com.tw/EAIService/", wsdlLocation = "http://10.1.6.46:9081/CWWSChannel/EAIService?wsdl")
public class EAIService_Service
    extends Service
{

    private final static URL EAISERVICE_WSDL_LOCATION;
    private final static WebServiceException EAISERVICE_EXCEPTION;
    private final static QName EAISERVICE_QNAME = new QName("http://www.bot.com.tw/EAIService/", "EAIService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.1.6.46:9081/CWWSChannel/EAIService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EAISERVICE_WSDL_LOCATION = url;
        EAISERVICE_EXCEPTION = e;
    }

    public EAIService_Service() {
        super(__getWsdlLocation(), EAISERVICE_QNAME);
    }

    public EAIService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EAISERVICE_QNAME, features);
    }

    public EAIService_Service(URL wsdlLocation) {
        super(wsdlLocation, EAISERVICE_QNAME);
    }

    public EAIService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EAISERVICE_QNAME, features);
    }

    public EAIService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EAIService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EAIService
     */
    @WebEndpoint(name = "EAIServicePort")
    public EAIService getEAIServicePort() {
        return super.getPort(new QName("http://www.bot.com.tw/EAIService/", "EAIServicePort"), EAIService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EAIService
     */
    @WebEndpoint(name = "EAIServicePort")
    public EAIService getEAIServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bot.com.tw/EAIService/", "EAIServicePort"), EAIService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EAISERVICE_EXCEPTION!= null) {
            throw EAISERVICE_EXCEPTION;
        }
        return EAISERVICE_WSDL_LOCATION;
    }

}
