
package com.eai.wsdl.sendRecv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EAIService", targetNamespace = "http://www.bot.com.tw/EAIService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EAIService {


    /**
     * 
     * @param rqXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.bot.com.tw/EAIService/sendRecv")
    @WebResult(name = "rsXml", targetNamespace = "")
    @RequestWrapper(localName = "sendRecv", targetNamespace = "http://www.bot.com.tw/EAIService/", className = "com.eai.ws.client.SendRecv")
    @ResponseWrapper(localName = "sendRecvResponse", targetNamespace = "http://www.bot.com.tw/EAIService/", className = "com.eai.ws.client.SendRecvResponse")
    public String sendRecv(
        @WebParam(name = "rqXml", targetNamespace = "")
        String rqXml);

}
