
package com.dataflux.wsdl.archserver.option;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataManagementServicePortType", targetNamespace = "http://archserver.wsdl.dataflux.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataManagementServicePortType {


    /**
     * 
     * @param table
     * @return
     *     returns com.dataflux.wsdl.archserver.option.TableOut
     */
    @WebMethod(operationName = "datasvc_MatchCodeOption.ddf_in", action = "MatchCodeOption.ddf*1*5ACE11B7D177F5C0")
    @WebResult(name = "table_", targetNamespace = "")
    @RequestWrapper(localName = "datasvc_MatchCodeOption.ddf_in", targetNamespace = "archserver.xsd.dataflux.com", className = "com.dataflux.wsdl.archserver.option.Request")
    @ResponseWrapper(localName = "datasvc_MatchCodeOption.ddf_out", targetNamespace = "archserver.xsd.dataflux.com", className = "com.dataflux.wsdl.archserver.option.Response")
    public TableOut datasvcMatchCodeOptionDdfIn(
        @WebParam(name = "table_", targetNamespace = "")
        TableIn table);

}
