
package com.dataflux.wsdl.archserver.option;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Data Management Server
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DMService", targetNamespace = "http://archserver.wsdl.dataflux.com", wsdlLocation = "file:/C:/Users/Sophia/AppData/Local/Temp/tempdir4086248199587773274.tmp/MatchCodeOption_1.wsdl")
public class DMService
    extends Service
{

    private final static URL DMSERVICE_WSDL_LOCATION;
    private final static WebServiceException DMSERVICE_EXCEPTION;
    private final static QName DMSERVICE_QNAME = new QName("http://archserver.wsdl.dataflux.com", "DMService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Sophia/AppData/Local/Temp/tempdir4086248199587773274.tmp/MatchCodeOption_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DMSERVICE_WSDL_LOCATION = url;
        DMSERVICE_EXCEPTION = e;
    }

    public DMService() {
        super(__getWsdlLocation(), DMSERVICE_QNAME);
    }

    public DMService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DMSERVICE_QNAME, features);
    }

    public DMService(URL wsdlLocation) {
        super(wsdlLocation, DMSERVICE_QNAME);
    }

    public DMService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DMSERVICE_QNAME, features);
    }

    public DMService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DMService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DataManagementServicePortType
     */
    @WebEndpoint(name = "DMService")
    public DataManagementServicePortType getDMService() {
        return super.getPort(new QName("http://archserver.wsdl.dataflux.com", "DMService"), DataManagementServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataManagementServicePortType
     */
    @WebEndpoint(name = "DMService")
    public DataManagementServicePortType getDMService(WebServiceFeature... features) {
        return super.getPort(new QName("http://archserver.wsdl.dataflux.com", "DMService"), DataManagementServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DMSERVICE_EXCEPTION!= null) {
            throw DMSERVICE_EXCEPTION;
        }
        return DMSERVICE_WSDL_LOCATION;
    }

}
